version: '3.8'
services:
  db:
    image: mysql:latest
    environment:
      - MYSQL_PORT=${DB_PORT}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
